# Generated by Django 5.1.1 on 2024-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
